name: smart_bazaar
description: "Smart Bazaar for E-Commerce"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  #Icons
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  url_launcher: ^6.3.0

  firebase_storage: ^12.1.1
  connectivity_plus: ^6.0.3


  #utility
  logger: ^2.4.0
  http: ^1.2.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
#Product Specific
  readmore: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  #------------------LOCAL ASSETS---------------------#
  assets:
   - assets/images/
   - assets/logos/
   - assets/icons/
   - assets/icons/brands/
   - assets/images/on_boarding_images/
   - assets/images/animations/
   - assets/icons/categories/
   - assets/images/banners/
   - assets/images/products/
   - assets/images/content/

#------------------LOCAL FONTS---------------------#
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Italic.ttf
         style: italic
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-MediumItalic.ttf
         weight: 500
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 800
       - asset: assets/fonts/Poppins-BoldItalic.ttf
         weight: 800
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         weight: 800


